package com.sners.snowforecast.view


import android.app.Activity
import android.content.Intent
import android.graphics.Color
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.animation.AnimationUtils
import android.widget.*
import androidx.databinding.DataBindingUtil
import com.sners.snowforecast.ForecastMainActivity
import com.sners.snowforecast.R
import com.sners.snowforecast.databinding.ActivityForecastMainBinding
import com.sners.snowforecast.databinding.DashboardBinding
import com.sners.snowforecast.weather.WeatherIconGallery
import kotlin.math.roundToInt

//TODO - Get icon from hourly, currently is giving me tosh
//TODO - Add binding to this class
//TODO - Fix rotating crash on launch screen

/**
 * A class representing the Dashboard view
 */
class WeatherDashboard : Activity() {

    /**
     * @property binding The binding class is autogenerated from the name of the layout it refers to
     */
    private lateinit var binding: DashboardBinding

     /**
     * @property hsvDashActivityIcons Activity icons scroll view
     */
    private var hsvDashActivityIcons: HorizontalScrollView? = null

    /**
     * @property llDashDashboard Linear Layout for the Dashboard - needed for animations
     */
    private var llDashDashboard: LinearLayout? = null

    /**
     * @property weatherData Weather data object
     */
    private var weatherData = ForecastMainActivity.weatherData!!

    /**
     * On Create - Override
     * @param savedInstanceState Saved instance state
     */
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.dashboard)

          hsvDashActivityIcons = findViewById<View>(R.id.hsvDashActivityIcons) as HorizontalScrollView
        llDashDashboard = findViewById<View>(R.id.llDashboard) as LinearLayout

        //Animation animExitLeft = AnimationUtils.makeInAnimation(this, false);
        //llDashDashboard.startAnimation(animExitLeft);
        binding.tvDashSummary.text = weatherData.headlineSummary
        binding.tvDashTimeTilSunset.text = String.format("%s", weatherData.getTimeTilSunsetString())

        //	timeTillPrecip
        binding.tvDashTimeTilPrecip.text = weatherData.precipitation!!.timeTilString(false)
        val iconName = weatherData.headlineIcon
        val iconId = resources.getIdentifier(iconName, "drawable", packageName)
        binding.ivDashSummary.setImageResource(iconId)
        binding.ivDashSummary.contentDescription = iconName
        setWeatherActivityIcons()

        populatePrecipitation()
        populateTemperature()
        populateWind()
    }

    /**
     * Set up weather activity icons
     */
    private fun setWeatherActivityIcons() {

        val iconGallery = WeatherIconGallery()
        val qualIcons = iconGallery.weatherActivityIcons
        inflateWeatherActivityIcons(qualIcons)
    }

    /**
     * Inflate weather activity icons
     * @param qualIcons Icons we want to show
     */
    private fun inflateWeatherActivityIcons(qualIcons: ArrayList<String>) {

        val layoutInflater = this.getSystemService(LAYOUT_INFLATER_SERVICE) as LayoutInflater
        binding.llDashIcontainer.removeAllViews()
        for (iconName in qualIcons) {
            val iconId = resources.getIdentifier(iconName, "drawable", packageName)
            val convertView = layoutInflater.inflate(R.layout.icon_gallery, null)
            val img = convertView.findViewById<View>(R.id.ivIconGalleryItem) as ImageView
            img.setImageResource(iconId)
            binding.llDashIcontainer.addView(convertView)
        }
    }

    /**
     * Populate Precipitation
     */
    private fun populatePrecipitation() {

        binding.tvDashPrecip.text = weatherData.precipitation!!.milsPerHourString
    }

    /**
     * Populate Temperature
     */
    private fun populateTemperature() {

        val tempString = weatherData.currently.temperature
        binding.tvDashTemperature.text = tempString
        val temperatureNum = weatherData.currently.temperatureNum.roundToInt()
        val tempColour = when (temperatureNum) {
            in Int.MIN_VALUE..0 -> Color.GRAY
            in 0..10 -> Color.BLUE
            in 10..15 -> Color.BLACK
            in 15..20 -> Color.rgb(254,211,0)  // Yellow
            in 20..25 -> Color.rgb(255,165,0) // Orange
            in 25..30 -> Color.MAGENTA
            in 30..Int.MAX_VALUE -> Color.RED
            else -> Color.YELLOW // This would indicate an error
        }
        binding.tvDashTemperature.setTextColor(tempColour)
    }


    /**
     * Populate Wind
     */
    private fun populateWind() {

        val beaufortValue = weatherData.wind!!.getSpeedBeaufort()
        binding.tvDashWind.text = "$beaufortValue"
        val windColour = when (beaufortValue) {
            in 5 .. 7 -> Color.MAGENTA
            in 7 .. Int.MAX_VALUE -> Color.RED
            else -> Color.parseColor("#008000") // Green
        }
        binding.tvDashWind.setTextColor(windColour)
    }

    ///////////////////////////////////////////
    //Activity ending events				 //
    ///////////////////////////////////////////
    /**
     * Display Current Weather
     * @param v View representing the current view - comes in from the layout
     */
    fun displayCurrent(v: View?) {

        val animExitLeft = AnimationUtils.makeOutAnimation(this, false)
        llDashDashboard!!.startAnimation(animExitLeft)
        Toast.makeText(
            applicationContext, "Show the weather",
            Toast.LENGTH_SHORT
        ).show()
        val currentIntent = Intent(this@WeatherDashboard, WeatherCurrent::class.java)
        startActivity(currentIntent)
        finish()
    }
}