package com.sners.ladiesagecalculator

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.ArrayAdapter
import android.widget.Toast
import androidx.databinding.DataBindingUtil
import com.sners.ladiesagecalculator.databinding.AgeCalcMainBinding
import com.sners.ladiesagecalculator.databinding.FragmentCalcBinding
import com.sners.ladiesagecalculator.databinding.FragmentTitleBinding


/**
 * A simple [Fragment] subclass.
 * Use the [CalcFragment.newInstance] factory method to
 * create an instance of this fragment.
 */
class CalcFragment : Fragment() {

    /**
     * @property binding The binding class is autogenerated from the name of the layout it refers to
     * 1. put the xml into a layout tag
     * 2. add this field
     * 3. replace setContentView with DataBindingUtil.setContentView
     */
    private lateinit var binding: FragmentCalcBinding

    /**
     * @property age Age object
     */
    private var age : Age = Age()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        // Inflate the layout for this fragment
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_calc, container, false)


        val monthNames = resources.getStringArray(R.array.months)

        val adapter: ArrayAdapter<String> =
             ArrayAdapter<String>(getActivity()!!.getApplicationContext(),
                 android.R.layout.simple_list_item_1, monthNames)

        binding.age = age

        binding.editMonth.threshold = 1
        binding.editMonth.setAdapter(adapter)

         binding.calculateButton.setOnClickListener {
              calculateAge()
          }



        return binding.root

    }


    private fun calculateAge() {
        //binding.ageCalculated.setText(getString(R.string.fabulous))
        age.flattery = getString(R.string.fabulous)
        Toast.makeText(activity, "You pressed calc", Toast.LENGTH_SHORT).show()

        binding.invalidateAll()
    }
}