package com.sners.ladiesagecalculator

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.databinding.DataBindingUtil
import androidx.navigation.Navigation
import com.sners.ladiesagecalculator.databinding.AgeCalcMainBinding
import com.sners.ladiesagecalculator.databinding.FragmentTitleBinding


/**
 * A simple [Fragment] subclass.
 * Use the [TitleFragment.newInstance] factory method to
 * create an instance of this fragment.
 */
class TitleFragment : Fragment() {
    /**
     * @property binding The binding class is autogenerated from the name of the layout it refers to
     * 1. put the xml into a layout tag
     * 2. add this field
     * 3. replace setContentView with DataBindingUtil.setContentView
     */
    private lateinit var binding: FragmentTitleBinding


    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        // Inflate the layout for this fragment
        binding = DataBindingUtil.inflate(inflater, R.layout.fragment_title, container, false)

        binding.goButton.setOnClickListener(
            Navigation.createNavigateOnClickListener(R.id.action_titleFragment_to_calcFragment)
        )
        return binding.root

    }


}